//! The Runtime executes commands emitted by the Engine against the storage backend.
//! It also handles storage reads needed for split-phase operations.

use crate::{
    engine::{
        commands::Command,
        Engine, EngineAction, LogSyncContinuation, SnapshotContinuation,
    },
    errors::{AnyError, StorageError, StorageOperation},
    storage::{Entry, Snapshot, SnapshotType, Storage, StorageOp},
    util::{IndexEntry, LogEntry, LogSync, SnapshottedEntry},
};
use std::{cmp::Ordering, marker::PhantomData, ops::RangeBounds};

/// Executes commands against storage and handles storage reads for the Engine.
pub(crate) struct Runtime<T: Entry, B: Storage<T>> {
    pub(crate) storage: B,
    _phantom: PhantomData<T>,
}

impl<T: Entry, B: Storage<T>> Runtime<T, B> {
    pub(crate) fn new(storage: B) -> Self {
        Runtime {
            storage,
            _phantom: PhantomData,
        }
    }

    /// Wrap an `AnyError` from a storage call into a `StorageError` with context.
    fn wrap_storage<V>(
        op: StorageOperation,
        result: Result<V, AnyError>,
    ) -> Result<V, StorageError> {
        result.map_err(|e| StorageError::new(op, e))
    }

    /// Execute all pending commands from the engine.
    pub(crate) async fn execute_commands(
        &mut self,
        commands: Vec<Command<T>>,
    ) -> Result<(), StorageError> {
        for cmd in commands {
            match cmd {
                Command::WriteAtomic(ops) => {
                    Self::wrap_storage(
                        StorageOperation::WriteAtomic,
                        self.storage.write_atomically(ops).await,
                    )?;
                }
                Command::AppendEntries(entries) => {
                    Self::wrap_storage(
                        StorageOperation::WriteAtomic,
                        self.storage
                            .write_atomically(vec![StorageOp::AppendEntries(entries)])
                            .await,
                    )?;
                }
            }
        }
        Ok(())
    }

    /// Handle an EngineAction that may require storage reads.
    pub(crate) async fn handle_action(
        &mut self,
        action: EngineAction<T>,
        engine: &mut Engine<T>,
    ) -> Result<(), StorageError> {
        match action {
            EngineAction::Done => Ok(()),
            EngineAction::NeedLogSync {
                from_idx,
                other_decided_idx,
                continuation,
            } => {
                let log_sync = self
                    .create_log_sync(engine, from_idx, other_decided_idx)
                    .await?;
                match continuation {
                    LogSyncContinuation::CompletePrepare {
                        prep_n,
                        from,
                        na,
                        accepted_idx,
                    } => {
                        engine.complete_prepare_with_sync(
                            prep_n,
                            from,
                            na,
                            accepted_idx,
                            log_sync,
                        );
                    }
                    LogSyncContinuation::CompleteAcceptSync { to } => {
                        engine.complete_accsync(to, log_sync);
                    }
                }
                // Execute any commands generated by the continuation
                let cmds = engine.take_commands();
                self.execute_commands(cmds).await
            }
            EngineAction::NeedMultipleLogSyncs(requests) => {
                for req in requests {
                    let log_sync = self
                        .create_log_sync(engine, req.from_idx, req.other_decided_idx)
                        .await?;
                    engine.complete_accsync(req.to, log_sync);
                }
                // Execute any commands generated by completions
                let cmds = engine.take_commands();
                self.execute_commands(cmds).await
            }
            EngineAction::NeedSnapshot {
                compact_idx: _,
                continuation,
            } => {
                // Handle snapshot creation - requires storage reads
                match continuation {
                    SnapshotContinuation::CompleteSnapshot { snapshot_idx, .. } => {
                        // Reuse existing try_snapshot flow, ignore errors
                        // (follower may not be caught up)
                        let _ = self.try_snapshot(engine, snapshot_idx).await;
                    }
                    SnapshotContinuation::CompleteSyncLogDelta { delta, compact_idx: _ } => {
                        let existing = Self::wrap_storage(
                            StorageOperation::ReadSnapshot,
                            self.storage.get_snapshot().await,
                        )?;
                        let merged = match existing {
                            Some(mut base) => {
                                base.merge(delta);
                                base
                            }
                            None => delta,
                        };
                        Self::wrap_storage(
                            StorageOperation::WriteAtomic,
                            self.storage
                                .write_atomically(vec![StorageOp::SetSnapshot(Some(merged))])
                                .await,
                        )?;
                    }
                }
                Ok(())
            }
        }
    }

    /// Build a LogSync from storage.
    async fn create_log_sync(
        &self,
        engine: &Engine<T>,
        common_prefix_idx: usize,
        other_logs_decided_idx: usize,
    ) -> Result<LogSync<T>, StorageError> {
        let decided_idx = engine.get_decided_idx();
        let (decided_snapshot, suffix, sync_idx) =
            if T::Snapshot::use_snapshots() && decided_idx > common_prefix_idx {
                let (delta_snapshot, compacted_idx) = self
                    .create_diff_snapshot(engine, other_logs_decided_idx)
                    .await?;
                let suffix = Self::wrap_storage(
                    StorageOperation::ReadSuffix,
                    self.storage.get_suffix(decided_idx).await,
                )?;
                (delta_snapshot, suffix, compacted_idx)
            } else {
                let suffix = Self::wrap_storage(
                    StorageOperation::ReadSuffix,
                    self.storage.get_suffix(common_prefix_idx).await,
                )?;
                (None, suffix, common_prefix_idx)
            };
        Ok(LogSync {
            decided_snapshot,
            suffix,
            sync_idx,
            stopsign: engine.get_stopsign(),
        })
    }

    /// Create a diff snapshot from storage.
    async fn create_diff_snapshot(
        &self,
        engine: &Engine<T>,
        from_idx: usize,
    ) -> Result<(Option<SnapshotType<T>>, usize), StorageError> {
        let log_decided_idx = engine.s.get_decided_idx_without_stopsign();
        let compacted_idx = engine.get_compacted_idx();
        let snapshot = if from_idx <= compacted_idx {
            if compacted_idx < log_decided_idx {
                Some(SnapshotType::Complete(
                    self.create_snapshot(engine, log_decided_idx).await?,
                ))
            } else {
                Self::wrap_storage(
                    StorageOperation::ReadSnapshot,
                    self.storage.get_snapshot().await,
                )?
                .map(SnapshotType::Complete)
            }
        } else {
            let diff_entries = Self::wrap_storage(
                StorageOperation::ReadEntries,
                self.storage.get_entries(from_idx, log_decided_idx).await,
            )?;
            Some(SnapshotType::Delta(T::Snapshot::create(
                diff_entries.as_slice(),
            )))
        };
        Ok((snapshot, log_decided_idx))
    }

    /// Create a snapshot from entries in storage.
    async fn create_snapshot(
        &self,
        engine: &Engine<T>,
        compact_idx: usize,
    ) -> Result<T::Snapshot, StorageError> {
        let current_compacted_idx = engine.get_compacted_idx();
        let entries = Self::wrap_storage(
            StorageOperation::ReadEntries,
            self.storage
                .get_entries(current_compacted_idx, compact_idx)
                .await,
        )?;
        let delta = T::Snapshot::create(entries.as_slice());
        match Self::wrap_storage(
            StorageOperation::ReadSnapshot,
            self.storage.get_snapshot().await,
        )? {
            Some(mut s) => {
                s.merge(delta);
                Ok(s)
            }
            None => Ok(delta),
        }
    }

    // --- Read methods for OmniPaxos public API ---

    /// Read entries in the range `r` in the log.
    pub(crate) async fn read<R>(
        &self,
        engine: &Engine<T>,
        r: R,
    ) -> Result<Option<Vec<LogEntry<T>>>, StorageError>
    where
        R: RangeBounds<usize>,
    {
        use std::ops::Bound;
        let from_idx = match r.start_bound() {
            Bound::Included(i) => *i,
            Bound::Excluded(e) => *e + 1,
            Bound::Unbounded => 0,
        };
        let to_idx = match r.end_bound() {
            Bound::Included(i) => *i + 1,
            Bound::Excluded(e) => *e,
            Bound::Unbounded => engine.get_accepted_idx(),
        };
        if to_idx == 0 {
            return Ok(None);
        }
        let compacted_idx = engine.get_compacted_idx();
        let accepted_idx = engine.get_accepted_idx();
        let to_type = match self.get_entry_type(engine, to_idx - 1, compacted_idx, accepted_idx)? {
            Some(IndexEntry::Compacted) => {
                return Ok(Some(vec![
                    self.create_compacted_entry(compacted_idx).await?,
                ]))
            }
            Some(from_type) => from_type,
            _ => return Ok(None),
        };
        let from_type = match self.get_entry_type(engine, from_idx, compacted_idx, accepted_idx)? {
            Some(from_type) => from_type,
            _ => return Ok(None),
        };
        match (from_type, to_type) {
            (IndexEntry::Entry, IndexEntry::Entry) => {
                Ok(Some(self.create_read_log_entries(engine, from_idx, to_idx).await?))
            }
            (IndexEntry::Entry, IndexEntry::StopSign(ss)) => {
                let mut entries = self.create_read_log_entries(engine, from_idx, to_idx - 1).await?;
                entries.push(LogEntry::StopSign(ss, engine.stopsign_is_decided()));
                Ok(Some(entries))
            }
            (IndexEntry::Compacted, IndexEntry::Entry) => {
                let mut entries = Vec::with_capacity(to_idx - compacted_idx + 1);
                entries.push(self.create_compacted_entry(compacted_idx).await?);
                let mut e = self.create_read_log_entries(engine, compacted_idx, to_idx).await?;
                entries.append(&mut e);
                Ok(Some(entries))
            }
            (IndexEntry::Compacted, IndexEntry::StopSign(ss)) => {
                let mut entries = Vec::with_capacity(to_idx - compacted_idx + 1);
                entries.push(self.create_compacted_entry(compacted_idx).await?);
                let mut e = self.create_read_log_entries(engine, compacted_idx, to_idx - 1).await?;
                entries.append(&mut e);
                entries.push(LogEntry::StopSign(ss, engine.stopsign_is_decided()));
                Ok(Some(entries))
            }
            (IndexEntry::StopSign(ss), IndexEntry::StopSign(_)) => {
                Ok(Some(vec![LogEntry::StopSign(ss, engine.stopsign_is_decided())]))
            }
            _ => Ok(None),
        }
    }

    /// Read all decided entries from `from_idx`.
    pub(crate) async fn read_decided_suffix(
        &self,
        engine: &Engine<T>,
        from_idx: usize,
    ) -> Result<Option<Vec<LogEntry<T>>>, StorageError> {
        let decided_idx = engine.get_decided_idx();
        if from_idx < decided_idx {
            self.read(engine, from_idx..decided_idx).await
        } else {
            Ok(None)
        }
    }

    fn get_entry_type(
        &self,
        engine: &Engine<T>,
        idx: usize,
        compacted_idx: usize,
        accepted_idx: usize,
    ) -> Result<Option<IndexEntry>, StorageError> {
        if idx < compacted_idx {
            Ok(Some(IndexEntry::Compacted))
        } else if idx + 1 < accepted_idx {
            Ok(Some(IndexEntry::Entry))
        } else if idx + 1 == accepted_idx {
            match engine.get_stopsign() {
                Some(ss) => Ok(Some(IndexEntry::StopSign(ss))),
                _ => Ok(Some(IndexEntry::Entry)),
            }
        } else {
            Ok(None)
        }
    }

    async fn create_read_log_entries(
        &self,
        engine: &Engine<T>,
        from: usize,
        to: usize,
    ) -> Result<Vec<LogEntry<T>>, StorageError> {
        let decided_idx = engine.get_decided_idx();
        let entries = Self::wrap_storage(
            StorageOperation::ReadEntries,
            self.storage.get_entries(from, to).await,
        )?
        .into_iter()
        .enumerate()
        .map(|(idx, e)| {
            let log_idx = idx + from;
            if log_idx < decided_idx {
                LogEntry::Decided(e)
            } else {
                LogEntry::Undecided(e)
            }
        })
        .collect();
        Ok(entries)
    }

    async fn create_compacted_entry(
        &self,
        compacted_idx: usize,
    ) -> Result<LogEntry<T>, StorageError> {
        Self::wrap_storage(
            StorageOperation::ReadSnapshot,
            self.storage.get_snapshot().await,
        )
        .map(|snap| match snap {
            Some(s) => LogEntry::Snapshotted(SnapshottedEntry::with(compacted_idx, s)),
            None => LogEntry::Trimmed(compacted_idx),
        })
    }

    /// Try snapshot (compaction with snapshot creation - needs storage reads).
    pub(crate) async fn try_snapshot(
        &mut self,
        engine: &mut Engine<T>,
        snapshot_idx: Option<usize>,
    ) -> Result<(), crate::CompactionErr> {
        let decided_idx = engine.get_decided_idx();
        let log_decided_idx = engine.s.get_decided_idx_without_stopsign();
        let new_compacted_idx = match snapshot_idx {
            Some(i) => match i.cmp(&decided_idx) {
                Ordering::Less => i,
                Ordering::Equal => log_decided_idx,
                Ordering::Greater => {
                    return Err(crate::CompactionErr::UndecidedIndex(decided_idx));
                }
            },
            None => log_decided_idx,
        };
        if new_compacted_idx > engine.get_compacted_idx() {
            let snapshot = self
                .create_snapshot(engine, new_compacted_idx)
                .await
                .map_err(crate::CompactionErr::Storage)?;
            Self::wrap_storage(
                StorageOperation::WriteAtomic,
                self.storage
                    .write_atomically(vec![
                        StorageOp::Trim(new_compacted_idx),
                        StorageOp::SetCompactedIdx(new_compacted_idx),
                        StorageOp::SetSnapshot(Some(snapshot)),
                    ])
                    .await,
            )
            .map_err(crate::CompactionErr::Storage)?;
            engine.s.compacted_idx = new_compacted_idx;
        }
        Ok(())
    }
}
